api:
  insecure: true

providers:
  docker:
    exposedByDefault: false

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

certificatesResolvers:
  localhost:
    acme:
      tlsChallenge: {}
      email: "ron.vanderheijden@pidz.nl"
      storage: "/letsencrypt/acme.json"

#log:
#  level: DEBUG
